# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/netbarry_fpga/netbarry_fpga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga || ORIG_REF_NAME==netbarry_fpga} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_processing_system7_0_0/netbarry_fpga_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_processing_system7_0_0 || ORIG_REF_NAME==netbarry_fpga_processing_system7_0_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_netbarry_core_0_0/netbarry_fpga_netbarry_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_netbarry_core_0_0 || ORIG_REF_NAME==netbarry_fpga_netbarry_core_0_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_blk_mem_gen_0_0/netbarry_fpga_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_blk_mem_gen_0_0 || ORIG_REF_NAME==netbarry_fpga_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_0/netbarry_fpga_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_gpio_0_0 || ORIG_REF_NAME==netbarry_fpga_axi_gpio_0_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_1/netbarry_fpga_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_gpio_0_1 || ORIG_REF_NAME==netbarry_fpga_axi_gpio_0_1} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_2/netbarry_fpga_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_gpio_0_2 || ORIG_REF_NAME==netbarry_fpga_axi_gpio_0_2} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_3/netbarry_fpga_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_gpio_0_3 || ORIG_REF_NAME==netbarry_fpga_axi_gpio_0_3} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_4/netbarry_fpga_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_gpio_0_4 || ORIG_REF_NAME==netbarry_fpga_axi_gpio_0_4} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_5/netbarry_fpga_axi_gpio_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_gpio_0_5 || ORIG_REF_NAME==netbarry_fpga_axi_gpio_0_5} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_gpio_0_6 || ORIG_REF_NAME==netbarry_fpga_axi_gpio_0_6} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_xbar_0/netbarry_fpga_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_xbar_0 || ORIG_REF_NAME==netbarry_fpga_xbar_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_ps7_0_axi_periph_0/netbarry_fpga_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_ps7_0_axi_periph_0 || ORIG_REF_NAME==netbarry_fpga_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_rst_ps7_0_100M_0/netbarry_fpga_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_rst_ps7_0_100M_0 || ORIG_REF_NAME==netbarry_fpga_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_axi_bram_ctrl_0_0/netbarry_fpga_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_axi_bram_ctrl_0_0 || ORIG_REF_NAME==netbarry_fpga_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_xlconstant_0_0/netbarry_fpga_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_xlconstant_0_0 || ORIG_REF_NAME==netbarry_fpga_xlconstant_0_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_7/netbarry_fpga_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_7 || ORIG_REF_NAME==netbarry_fpga_auto_pc_7} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_0/netbarry_fpga_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_0 || ORIG_REF_NAME==netbarry_fpga_auto_pc_0} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_1/netbarry_fpga_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_1 || ORIG_REF_NAME==netbarry_fpga_auto_pc_1} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_2/netbarry_fpga_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_2 || ORIG_REF_NAME==netbarry_fpga_auto_pc_2} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_3/netbarry_fpga_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_3 || ORIG_REF_NAME==netbarry_fpga_auto_pc_3} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_4/netbarry_fpga_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_4 || ORIG_REF_NAME==netbarry_fpga_auto_pc_4} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_5/netbarry_fpga_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_5 || ORIG_REF_NAME==netbarry_fpga_auto_pc_5} -quiet] -quiet

# IP: bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_6/netbarry_fpga_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==netbarry_fpga_auto_pc_6 || ORIG_REF_NAME==netbarry_fpga_auto_pc_6} -quiet] -quiet

# XDC: bd/netbarry_fpga/netbarry_fpga_ooc.xdc
