# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.cache/wt [current_project]
set_property parent.project_path /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/hdl/netbarry_fpga_wrapper.v
add_files /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/netbarry_fpga.bd
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_processing_system7_0_0/netbarry_fpga_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_blk_mem_gen_0_0/netbarry_fpga_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_0/netbarry_fpga_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_0/netbarry_fpga_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_0/netbarry_fpga_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_1/netbarry_fpga_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_1/netbarry_fpga_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_1/netbarry_fpga_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_2/netbarry_fpga_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_2/netbarry_fpga_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_2/netbarry_fpga_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_3/netbarry_fpga_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_3/netbarry_fpga_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_3/netbarry_fpga_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_4/netbarry_fpga_axi_gpio_0_4_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_4/netbarry_fpga_axi_gpio_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_4/netbarry_fpga_axi_gpio_0_4.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_5/netbarry_fpga_axi_gpio_0_5_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_5/netbarry_fpga_axi_gpio_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_5/netbarry_fpga_axi_gpio_0_5.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_xbar_0/netbarry_fpga_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_rst_ps7_0_100M_0/netbarry_fpga_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_rst_ps7_0_100M_0/netbarry_fpga_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_rst_ps7_0_100M_0/netbarry_fpga_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_bram_ctrl_0_0/netbarry_fpga_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_7/netbarry_fpga_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_0/netbarry_fpga_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_1/netbarry_fpga_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_2/netbarry_fpga_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_3/netbarry_fpga_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_4/netbarry_fpga_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_5/netbarry_fpga_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_auto_pc_6/netbarry_fpga_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/netbarry_fpga_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top netbarry_fpga_wrapper -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef netbarry_fpga_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file netbarry_fpga_wrapper_utilization_synth.rpt -pb netbarry_fpga_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
