# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6.xci
# IP: The module: 'netbarry_fpga_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'netbarry_fpga_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'netbarry_fpga_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'netbarry_fpga_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6.xci
# IP: The module: 'netbarry_fpga_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'netbarry_fpga_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'netbarry_fpga_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guy/Documents/NetBarry/NetBarry/NetBarry/NetBarry.srcs/sources_1/bd/netbarry_fpga/ip/netbarry_fpga_axi_gpio_0_6/netbarry_fpga_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'netbarry_fpga_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
